name: GitHub Pages Deploy

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

env: 
  MDBOOK_VERSION: v0.4.28

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download mdBook
        run: |
          curl -L https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
            > mdbook.tar.gz

      - name: Unzip
        run: tar -zxvf ./mdbook.tar.gz

      - name: Build
        run: ./mdbook build

      - name: Deploy to GH Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book
